name: Deploy to PyPI

on:
  # push:
  #   tags:
  #     - "*"
  # workflow_dispatch:
  push:
    branches:
      - main
      - ci-cd
    tags-ignore:
      - "*"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

  unit-test:
      runs-on: ubuntu-latest
      needs: install-dependencies
      steps:
        - name: Install dev dependencies
          run: pip install pytest

        - name: Run tests
          run: pytest tests
  
  deploy-to-pypi:
      runs-on: ubuntu-latest
      needs: unit-test
      steps:
        - name: Install build and deploy dependencies      
          run: pip install --upgrade build twine
        
        - name: Build package
          run: python -m build
        
        - name: Upload package to PyPI
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          run: python -m twine upload --repository testpypi dist/*
        